BAH-2334|Added repository trigger job
Co-authored-by: Umair Fayaz <omayrfayaz@gmail.com>

diff --git a/.github/workflows/build_publish.yaml b/.github/workflows/build_publish.yaml
--- a/.github/workflows/build_publish.yaml
+++ b/.github/workflows/build_publish.yaml
@@ -23,7 +23,7 @@ jobs:
       - name: Upload bahmni-connect-apps.zip
         uses: actions/upload-artifact@v2
         with:
-          name: bahmni-connect-apps
+          name: bahmni-connect-apps-zip
           path: | 
             bahmni-connect-apps.zip
       - name: Upload androidDist as Artifact
@@ -32,3 +32,23 @@ jobs:
           name: bahmni-android
           path: | 
             ui/androidDist
+
+  trigger-dependent-repos:
+    name: Trigger Workflows
+    runs-on: ubuntu-latest
+    needs: build-publish
+    steps:
+      - name: Create repository_dispatch
+        env:
+          REPOSITORY_NAME: bahmni-offline
+          ORG_NAME: Bahmni
+          EVENT_TYPE: bahmni-connect-trigger
+        run: |
+          trigger_result=$(curl -s -o trigger_response.txt -w "%{http_code}" -X POST -H "Accept: application/vnd.github.v3+json" -H 'authorization: Bearer ${{ secrets.BAHMNI_PAT }}' https://api.github.com/repos/${ORG_NAME}/${REPOSITORY_NAME}/dispatches -d '{"event_type":"'"${EVENT_TYPE}"'"}')
+          if [ $trigger_result == 204 ];then
+            echo "Trigger to $ORG_NAME/$REPOSITORY_NAME Success"
+          else
+            echo "Trigger to $ORG_NAME/$REPOSITORY_NAME Failed"
+            cat trigger_response.txt
+            exit 1
+          fi  
